# Generated by Django 5.2.7 on 2025-11-28 04:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('tracet', '0001_initial'), ('tracet', '0002_alter_mwa_trigger'), ('tracet', '0003_alter_gcnstream_name'), ('tracet', '0004_eventgroup_time'), ('tracet', '0005_containscondition'), ('tracet', '0006_rename_event_notice_and_more'), ('tracet', '0007_rename_events_eventgroup_notices'), ('tracet', '0008_rename_eventgroup_event'), ('tracet', '0009_remove_mwa_minimum_altitude_mwa_exposure_mwa_nobs_and_more'), ('tracet', '0010_mwa_password'), ('tracet', '0011_observation_alter_mwa_frequency'), ('tracet', '0012_trigger_priority'), ('tracet', '0013_remove_trigger_active_trigger_testing'), ('tracet', '0014_remove_trigger_testing_trigger_active_and_more'), ('tracet', '0015_rename_success_observation_status'), ('tracet', '0016_rename_end_observation_finish_and_more'), ('tracet', '0017_alter_observation_status'), ('tracet', '0018_remove_observation_status_observation_istest_and_more'), ('tracet', '0019_observation_event_observation_trigger'), ('tracet', '0020_atca_bandconfig'), ('tracet', '0021_atca_trigger'), ('tracet', '0022_rename_bandconfig_atcaband'), ('tracet', '0023_atca_authentication_token_atca_email_and_more'), ('tracet', '0024_mwa_tileset_alter_atca_maximum_lag_and_more'), ('tracet', '0025_alter_mwa_tileset'), ('tracet', '0026_alter_booleancondition_if_false_and_more'), ('tracet', '0027_alter_decision_event_alter_factor_vote'), ('tracet', '0028_remove_decision_type_decision_simulated')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GCNStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('type', models.CharField(choices=[('xml', 'XML'), ('json', 'JSON')], default='xml', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('payload', models.BinaryField()),
                ('istest', models.BooleanField(default=False)),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracet.gcnstream')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('active', models.BooleanField(default=False, help_text='Is this trigger active? Set to inactive during testing to avoid sending spurious triggers to observatories.')),
                ('groupby', models.CharField(max_length=500)),
                ('ra_path', models.CharField(max_length=500)),
                ('dec_path', models.CharField(max_length=500)),
                ('time_path', models.CharField(help_text='The (x|j)json path to event time. This value is set by the first matching event and is not overridden by subsequent events.', max_length=250)),
                ('streams', models.ManyToManyField(to='tracet.gcnstream')),
            ],
        ),
        migrations.CreateModel(
            name='NumericRangeCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selector', models.CharField(max_length=250)),
                ('val1', models.FloatField(verbose_name='≥')),
                ('val2', models.FloatField(verbose_name='＜')),
                ('if_true', models.IntegerField(choices=[(1, 'Pass'), (0, 'Maybe'), (-1, 'Fail')])),
                ('if_false', models.IntegerField(choices=[(1, 'Pass'), (0, 'Maybe'), (-1, 'Fail')])),
                ('trigger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracet.trigger')),
            ],
        ),
        migrations.CreateModel(
            name='MWA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectid', models.CharField(max_length=500)),
                ('repointing_threshold', models.FloatField()),
                ('frequency', models.CharField(max_length=500)),
                ('frequency_resolution', models.FloatField()),
                ('time_resolution', models.FloatField()),
                ('minimum_altitude', models.FloatField()),
                ('maximum_window', models.IntegerField(help_text='The maximum window of time following an event in which observations maybe be scheduled. Observations will may be truncated to not exceed this window, and events occurring after this window will be ignored. [second]')),
                ('trigger', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tracet.trigger')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupid', models.CharField(max_length=500)),
                ('events', models.ManyToManyField(to='tracet.event')),
                ('trigger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracet.trigger')),
            ],
        ),
        migrations.CreateModel(
            name='BooleanCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selector', models.CharField(max_length=250)),
                ('if_true', models.IntegerField(choices=[(1, 'Pass'), (0, 'Maybe'), (-1, 'Fail')])),
                ('if_false', models.IntegerField(choices=[(1, 'Pass'), (0, 'Maybe'), (-1, 'Fail')])),
                ('trigger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracet.trigger')),
            ],
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['-created'], name='tracet__created_d60b86_idx'),
        ),
        migrations.AlterField(
            model_name='mwa',
            name='trigger',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='tracet.trigger'),
        ),
        migrations.AlterField(
            model_name='gcnstream',
            name='name',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AddField(
            model_name='eventgroup',
            name='time',
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name='ContainsCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selector', models.CharField(max_length=250)),
                ('vals', models.TextField()),
                ('if_true', models.IntegerField(choices=[(1, 'Pass'), (0, 'Maybe'), (-1, 'Fail')])),
                ('if_false', models.IntegerField(choices=[(1, 'Pass'), (0, 'Maybe'), (-1, 'Fail')])),
                ('trigger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracet.trigger')),
            ],
        ),
        migrations.RenameModel(
            old_name='Event',
            new_name='Notice',
        ),
        migrations.RenameIndex(
            model_name='notice',
            new_name='tracet__created_d60b86_idx',
            old_name='tracet__created_d518f6_idx',
        ),
        migrations.AlterField(
            model_name='trigger',
            name='time_path',
            field=models.CharField(help_text='The (x|j)json path to event time. This value is set by the first matching notice and is not overridden by subsequent notices.', max_length=250),
        ),
        migrations.RenameField(
            model_name='eventgroup',
            old_name='events',
            new_name='notices',
        ),
        migrations.RenameModel(
            old_name='EventGroup',
            new_name='Event',
        ),
        migrations.RemoveField(
            model_name='mwa',
            name='minimum_altitude',
        ),
        migrations.AddField(
            model_name='mwa',
            name='exposure',
            field=models.FloatField(default=120, help_text='The duration of each observation (for each frequency range). [second]'),
        ),
        migrations.AddField(
            model_name='mwa',
            name='nobs',
            field=models.IntegerField(default=15, help_text='The total number of observations. The total time will equal: (nobs) * (number of frequency ranges) * (exposure time)'),
        ),
        migrations.AlterField(
            model_name='mwa',
            name='frequency_resolution',
            field=models.FloatField(default=10, help_text='Correlator frequency resolution. [kHz]'),
        ),
        migrations.AlterField(
            model_name='mwa',
            name='time_resolution',
            field=models.FloatField(default=0.5, help_text='Correlator integration time. [second]'),
        ),
        migrations.AddField(
            model_name='mwa',
            name='password',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mwa',
            name='frequency',
            field=models.CharField(help_text="A space separated list of MWA coarse channel specifications. The specification format is documented <a href='https://mwatelescope.atlassian.net/wiki/spaces/MP/pages/24972656/Triggering+web+services#Channel-selection-specifier-strings'>here.</a> For example: '145,24' will observe with 24 channels centered at channel 145; a space separated list like '121:24 145:160;165:170' will schedule two separate observations.", max_length=500),
        ),
        migrations.AddField(
            model_name='trigger',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='trigger',
            name='active',
        ),
        migrations.AddField(
            model_name='trigger',
            name='active',
            field=models.BooleanField(default=False, help_text='Inactive triggers will send observation requests to observatories marked as testing only.'),
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observatory', models.CharField(max_length=500)),
                ('priority', models.IntegerField()),
                ('start', models.DateTimeField(default=django.utils.timezone.now)),
                ('finish', models.DateTimeField()),
                ('log', models.TextField()),
                ('istest', models.BooleanField(default=True)),
                ('success', models.BooleanField(default=True)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracet.event')),
                ('trigger', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracet.trigger')),
            ],
        ),
        migrations.CreateModel(
            name='ATCA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectid', models.CharField(max_length=500)),
                ('trigger', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='tracet.trigger')),
                ('authentication_token', models.CharField(default='', max_length=500)),
                ('email', models.EmailField(default='', help_text='The email address that was supplied in the NAPA proposal.', max_length=254)),
                ('http_password', models.CharField(default='', max_length=500, verbose_name='HTTP Password')),
                ('http_username', models.CharField(default='', max_length=500, verbose_name='HTTP Username')),
                ('maximum_exposure', models.IntegerField(default=120, help_text='The maximum exposure time required for this trigger. [minute]')),
                ('maximum_lag', models.FloatField(help_text='The maximum delay allowed for scheduling this observation. If the observation cannot be scheduled to start within this time, it will not be scheduled at all. [minute]')),
                ('minimum_exposure', models.IntegerField(default=30, help_text='The minimum exposure time required for this trigger. The trigger will be rejected if ATCA cannot schedule a total exposure of at least this time. [minute]')),
            ],
        ),
        migrations.CreateModel(
            name='ATCABand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band', models.IntegerField(choices=[(3, '3mm'), (7, '6mm'), (15, '15mm'), (40, '4cm'), (160, '16cm')])),
                ('freq1', models.IntegerField(help_text='Specify the central frequency for the first of the 2 GHz bands at which this receiver will observe. Note: the 16 cm reciever can only observe at 2100 MHz. [MHz]')),
                ('freq2', models.IntegerField(help_text='Specify the central frequency for the second of the 2 GHz bands at which this receiver will observe. Note: the 16 cm reciever can only observe at 2100 MHz. [MHz]')),
                ('atca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracet.atca')),
                ('exposure', models.IntegerField(default=1, help_text='The exposure time of this reciever. Receivers will be continuously cycled up until the full scheduled slot is exhausted. [minute]')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('atca', 'band'), name='unique wavelength configuration')],
            },
        ),
        migrations.AddField(
            model_name='mwa',
            name='tileset',
            field=models.CharField(choices=[('phase_one', 'Phase 1'), ('p1+hexes', 'Phase 1 + Hexes'), ('p1+solar', 'Phase 1 + Solar'), ('p2_compact', 'Phase 2 Compact'), ('p2_extended', 'Phase 2 Extended'), ('256T', '256 tiles')], help_text='Select the set of tiles to use for this observation. More tiles gives better sensitivity but at the expense larger data requirements.'),
        ),
        migrations.AlterField(
            model_name='booleancondition',
            name='if_false',
            field=models.IntegerField(choices=[(-1, 'Fail'), (0, 'Maybe'), (1, 'Pass')]),
        ),
        migrations.AlterField(
            model_name='booleancondition',
            name='if_true',
            field=models.IntegerField(choices=[(-1, 'Fail'), (0, 'Maybe'), (1, 'Pass')]),
        ),
        migrations.AlterField(
            model_name='containscondition',
            name='if_false',
            field=models.IntegerField(choices=[(-1, 'Fail'), (0, 'Maybe'), (1, 'Pass')]),
        ),
        migrations.AlterField(
            model_name='containscondition',
            name='if_true',
            field=models.IntegerField(choices=[(-1, 'Fail'), (0, 'Maybe'), (1, 'Pass')]),
        ),
        migrations.AlterField(
            model_name='numericrangecondition',
            name='if_false',
            field=models.IntegerField(choices=[(-1, 'Fail'), (0, 'Maybe'), (1, 'Pass')]),
        ),
        migrations.AlterField(
            model_name='numericrangecondition',
            name='if_true',
            field=models.IntegerField(choices=[(-1, 'Fail'), (0, 'Maybe'), (1, 'Pass')]),
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='tracet.event')),
                ('simulated', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Factor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.TextField()),
                ('vote', models.IntegerField(blank=True, choices=[(-1, 'Fail'), (0, 'Maybe'), (1, 'Pass')], null=True)),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factors', to='tracet.decision')),
            ],
        ),
    ]
