# Generated by Django 5.2.7 on 2025-11-28 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracet', '0001_squashed_0028_remove_decision_type_decision_simulated'),
    ]

    operations = [
        migrations.AddField(
            model_name='factor',
            name='inherited',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='atca',
            name='authentication_token',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='atca',
            name='email',
            field=models.EmailField(help_text='The email address that was supplied in the NAPA proposal.', max_length=254),
        ),
        migrations.AlterField(
            model_name='atca',
            name='http_password',
            field=models.CharField(max_length=500, verbose_name='HTTP Password'),
        ),
        migrations.AlterField(
            model_name='atca',
            name='http_username',
            field=models.CharField(max_length=500, verbose_name='HTTP Username'),
        ),
        migrations.AlterField(
            model_name='atca',
            name='maximum_exposure',
            field=models.IntegerField(help_text='The maximum exposure time required for this trigger. [minute]'),
        ),
        migrations.AlterField(
            model_name='atca',
            name='minimum_exposure',
            field=models.IntegerField(help_text='The minimum exposure time required for this trigger. The trigger will be rejected if ATCA cannot schedule a total exposure of at least this time. [minute]'),
        ),
        migrations.AlterField(
            model_name='atca',
            name='trigger',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='tracet.trigger'),
        ),
        migrations.AlterField(
            model_name='atcaband',
            name='exposure',
            field=models.IntegerField(help_text='The exposure time of this reciever. Receivers will be continuously cycled up until the full scheduled slot is exhausted. [minute]'),
        ),
        migrations.AlterField(
            model_name='decision',
            name='simulated',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='observation',
            name='istest',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='observation',
            name='success',
            field=models.BooleanField(),
        ),
    ]
