# Generated by Django 5.2.7 on 2025-12-10 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracet', '0029_factor_inherited_alter_atca_authentication_token_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mwa',
            old_name='password',
            new_name='secure_key',
        ),
        migrations.AlterField(
            model_name='numericrangecondition',
            name='val1',
            field=models.FloatField(verbose_name='Lower bound'),
        ),
        migrations.AlterField(
            model_name='numericrangecondition',
            name='val2',
            field=models.FloatField(verbose_name='Upper bound'),
        ),
    ]
