# Generated by Django 5.2.7 on 2025-12-11 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracet', '0030_rename_password_mwa_secure_key_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-time']},
        ),
        migrations.AlterField(
            model_name='mwa',
            name='tileset',
            field=models.CharField(choices=[('phase_one', 'Phase 1'), ('p1+hexes', 'Phase 1 + Hexes'), ('p1+solar', 'Phase 1 + Solar'), ('p2_compact', 'Phase 2 Compact'), ('p2_extended', 'Phase 2 Extended'), ('256T', '256 tiles')], help_text='Select the set of tiles to use for this observation. More tiles gives better sensitivity but at the expense of larger data requirements.'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['-time'], name='tracet__time_aa3832_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['groupid'], name='tracet__groupid_6ebfe1_idx'),
        ),
    ]
