# Generated by Django 6.0 on 2025-12-15 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracet', '0031_alter_event_options_alter_mwa_tileset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='decision',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracet.decision'),
        ),
        migrations.AlterField(
            model_name='atcaband',
            name='freq1',
            field=models.IntegerField(help_text='Specify the central frequency for the first of the 2 GHz bands at which this receiver will observe. Note: the 16 cm reciever can only observe at 2100 MHz. [MHz]', verbose_name='Frequency 1'),
        ),
        migrations.AlterField(
            model_name='atcaband',
            name='freq2',
            field=models.IntegerField(help_text='Specify the central frequency for the second of the 2 GHz bands at which this receiver will observe. Note: the 16 cm reciever can only observe at 2100 MHz. [MHz]', verbose_name='Frequency 2'),
        ),
    ]
