# Generated by Django 6.0 on 2025-12-15 02:20
from datetime import timedelta

from django.db import migrations


def add_observations(apps, schema_editor):
    Decision = apps.get_model("tracet", "Decision")

    for decision in Decision.objects.filter(simulated=False):
        observations = decision.event.observation_set.filter(
            start__gt=decision.created,
            start__lt=decision.created + timedelta(seconds=2),
        )
        if len(observations) == 1:
            observation = observations.first()
            observation.decision = decision
            observation.save()


class Migration(migrations.Migration):
    dependencies = [
        ("tracet", "0032_observation_decision_alter_atcaband_freq1_and_more"),
    ]

    operations = [migrations.RunPython(add_observations)]
