# Generated by Django 6.0 on 2025-12-15 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracet', '0033_auto_20251215_0220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observation',
            old_name='start',
            new_name='created',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='event',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='success',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='trigger',
        ),
        migrations.AddField(
            model_name='observation',
            name='status',
            field=models.CharField(choices=[('api_ok', 'OK'), ('api_failure', 'Failure'), ('clash', 'Already observing'), ('request_failure', 'Unable to prepare request')], default='api_ok'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='observation',
            name='finish',
            field=models.DateTimeField(null=True),
        ),
    ]
