# Generated by Django 6.0 on 2025-12-15 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracet', '0034_rename_start_observation_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='decision',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracet.decision'),
        ),
    ]
