# Generated by Django 6.0 on 2025-12-15 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracet', '0036_alter_observation_decision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='status',
            field=models.CharField(choices=[('api_ok', 'OK'), ('api_failure', 'Failure'), ('clash', 'Already observing'), ('request_failure', 'Could not make API request'), ('data_failure', 'Unable to prepare request')]),
        ),
    ]
