# Generated by Django 6.0 on 2025-12-16 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracet', '0038_alter_observation_observatory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='status',
            field=models.CharField(choices=[('api_ok', 'OK'), ('api_failure', 'Failure'), ('clash', 'Clashing observation'), ('request_failure', 'Could not make API request'), ('data_failure', 'Unable to prepare request'), ('unknown_failure', 'An unexpected failure occurred')]),
        ),
    ]
