# Generated by Django 6.0 on 2025-12-16 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracet', '0039_alter_observation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='decision',
            name='source',
            field=models.CharField(choices=[('notice', 'Notice'), ('manual', 'Manually triggered'), ('simulated', 'Simulated')], default='manual'),
            preserve_default=False,
        ),
    ]
