# Generated by Django 6.0 on 2025-12-16 07:34
from datetime import timedelta

from django.db import migrations

from tracet import models


def set_decision_source(apps, schema_editor):
    Decision = apps.get_model("tracet", "Decision")

    for decision in Decision.objects.all():
        if decision.simulated:
            decision.source = models.Decision.Source.SIMULATED
        else:
            notices = decision.event.notices.filter(
                created__lte=decision.created,
                created__gt=decision.created - timedelta(seconds=2),
            )
            if len(notices):
                decision.source = models.Decision.Source.NOTICE
            else:
                decision.source = models.Decision.Source.MANUAL

        decision.save()


class Migration(migrations.Migration):
    dependencies = [
        ("tracet", "0040_decision_source"),
    ]

    operations = [migrations.RunPython(set_decision_source)]
