# Generated by Django 6.0 on 2025-12-16 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracet', '0041_auto_20251216_0734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decision',
            name='simulated',
        ),
    ]
