# Generated by Django 6.0 on 2025-12-17 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracet', '0042_remove_decision_simulated'),
    ]

    operations = [
        migrations.AddField(
            model_name='atca',
            name='dec_path',
            field=models.CharField(default='', help_text='The (x|j)path to the Declination. This value is set by the most recent matching notice.', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atca',
            name='ra_path',
            field=models.CharField(default='', help_text='The (x|j)path to the Right Ascension. This value is set by the most recent matching notice.', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mwa',
            name='dec_path',
            field=models.CharField(default='', help_text='The (x|j)path to the Declination. This value is set by the most recent matching notice.', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mwa',
            name='ra_path',
            field=models.CharField(default='', help_text='The (x|j)path to the Right Ascension. This value is set by the most recent matching notice.', max_length=500),
            preserve_default=False,
        ),
    ]
