# Generated by Django 6.0 on 2025-12-17 01:59

from django.db import migrations


def set_radec_paths(apps, schema_editor):
    MWA = apps.get_model("tracet", "MWA")
    ATCA = apps.get_model("tracet", "ATCA")

    for telescope in [*MWA.objects.all(), *ATCA.objects.all()]:
        telescope.ra_path = telescope.trigger.ra_path
        telescope.dec_path = telescope.trigger.dec_path
        telescope.save()


class Migration(migrations.Migration):
    dependencies = [
        ("tracet", "0043_atca_dec_path_atca_ra_path_mwa_dec_path_mwa_ra_path"),
    ]

    operations = [migrations.RunPython(set_radec_paths)]
