# Generated by Django 6.0 on 2025-12-17 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracet', '0046_rename_mwa_mwacorrelator'),
    ]

    operations = [
        migrations.CreateModel(
            name='MWAVCS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectid', models.CharField(max_length=500)),
                ('secure_key', models.CharField(max_length=500)),
                ('repointing_threshold', models.FloatField()),
                ('tileset', models.CharField(choices=[('phase_one', 'Phase 1'), ('p1+hexes', 'Phase 1 + Hexes'), ('p1+solar', 'Phase 1 + Solar'), ('p2_compact', 'Phase 2 Compact'), ('p2_extended', 'Phase 2 Extended'), ('256T', '256 tiles')], help_text='Select the set of tiles to use for this observation. More tiles gives better sensitivity but at the expense of larger data requirements.')),
                ('frequency', models.CharField(help_text="A space separated list of MWA coarse channel specifications. The specification format is documented <a href='https://mwatelescope.atlassian.net/wiki/spaces/MP/pages/24972656/Triggering+web+services#Channel-selection-specifier-strings'>here.</a> For example: '145,24' will observe with 24 channels centered at channel 145; a space separated list like '121:24 145:160;165:170' will schedule two separate observations.", max_length=500)),
                ('frequency_resolution', models.FloatField(default=10, help_text='Correlator frequency resolution. [kHz]')),
                ('time_resolution', models.FloatField(default=0.5, help_text='Correlator integration time. [second]')),
                ('exposure', models.FloatField(default=120, help_text='The duration of each observation (for each frequency range). [second]')),
                ('nobs', models.IntegerField(default=15, help_text='The total number of observations. The total time will equal: (nobs) * (number of frequency ranges) * (exposure time)')),
                ('maximum_window', models.IntegerField(help_text='The maximum window of time following an event in which observations maybe be scheduled. Observations will may be truncated to not exceed this window, and events occurring after this window will be ignored. [second]')),
                ('ra_path', models.CharField(help_text='The (x|j)path to the Right Ascension. This value is set by the most recent matching notice.', max_length=500)),
                ('dec_path', models.CharField(help_text='The (x|j)path to the Declination. This value is set by the most recent matching notice.', max_length=500)),
                ('trigger', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='tracet.trigger')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
