# Generated by Django 6.0 on 2026-01-08 02:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracet', '0048_mwagw'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='event',
            new_name='tracet_even_time_847bd6_idx',
            old_name='tracet__time_aa3832_idx',
        ),
        migrations.RenameIndex(
            model_name='event',
            new_name='tracet_even_groupid_ebc7ca_idx',
            old_name='tracet__groupid_6ebfe1_idx',
        ),
        migrations.RenameIndex(
            model_name='notice',
            new_name='tracet_noti_created_533d2a_idx',
            old_name='tracet__created_d60b86_idx',
        ),
        migrations.AddField(
            model_name='trigger',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
