# Generated by Django 6.0 on 2026-01-08 07:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracet', '0049_rename_tracet__time_aa3832_idx_tracet_even_time_847bd6_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trigger',
            name='created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
