# Generated by Django 6.0 on 2026-01-14 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracet', '0050_trigger_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atcaband',
            name='atca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atcabands', to='tracet.atca'),
        ),
        migrations.AlterField(
            model_name='booleancondition',
            name='trigger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booleanconditions', to='tracet.trigger'),
        ),
        migrations.AlterField(
            model_name='containscondition',
            name='trigger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='containsconditions', to='tracet.trigger'),
        ),
        migrations.AlterField(
            model_name='event',
            name='trigger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tracet.trigger'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='stream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='tracet.gcnstream'),
        ),
        migrations.AlterField(
            model_name='numericrangecondition',
            name='trigger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numericrangeconditions', to='tracet.trigger'),
        ),
    ]
