# Generated by Django 6.0 on 2026-01-14 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracet', '0051_alter_atcaband_atca_alter_booleancondition_trigger_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trigger',
            name='expiry',
            field=models.FloatField(default=30, help_text='Events will expire once this duration has elapsed since first notice. Subsequent notices will not trigger automated observations; manual retriggers will ignore this condition. [minute]'),
            preserve_default=False,
        ),
    ]
