# Generated by Django 6.0 on 2026-01-20 06:20
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracet', '0052_trigger_expiry'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContainsCondition',
            new_name='EqualityCondition',
        ),
    ]
