# Generated by Django 6.0 on 2026-01-20 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracet', '0053_rename_containscondition_to_equalitycondition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equalitycondition',
            name='trigger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equalityconditions', to='tracet.trigger'),
        ),
        migrations.AlterField(
            model_name='equalitycondition',
            name='vals',
            field=models.TextField(help_text='Enter one more or more candidates (one per line) to test for equality with the selector.', verbose_name='Candidates'),
        ),
    ]
