# Generated by Django 6.0 on 2026-01-21 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracet', '0054_alter_equalitycondition_trigger_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='configuation',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
