# Generated by Django 6.0 on 2026-01-21 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracet', '0055_observation_configuation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observation',
            old_name='configuation',
            new_name='configuration',
        ),
    ]
