# Generated by Django 6.0 on 2026-01-22 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracet', '0056_rename_configuation_observation_configuration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mwacorrelator',
            name='maximum_window',
        ),
        migrations.RemoveField(
            model_name='mwagw',
            name='maximum_window',
        ),
        migrations.RemoveField(
            model_name='mwavcs',
            name='maximum_window',
        ),
    ]
