# Generated by Django 6.0 on 2026-01-22 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracet', '0057_remove_mwacorrelator_maximum_window_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='pointing',
            field=models.JSONField(default=list),
        ),
    ]
