# Generated by Django 6.0 on 2026-01-22 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracet', '0058_observation_pointing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observation',
            old_name='pointing',
            new_name='_pointing',
        ),
    ]
