# Generated by Django 6.0 on 2026-01-22 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracet', '0059_rename_pointing_observation__pointing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observation',
            old_name='_pointing',
            new_name='_pointings',
        ),
    ]
