# Generated by Django 6.0 on 2026-01-23 07:16

import tracet.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracet', '0060_rename__pointing_observation__pointings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atca',
            name='dec_path',
            field=tracet.models.fields.JXPathField(help_text='The (x|j)path to the Declination. This value is set by the most recent matching notice.', max_length=500),
        ),
        migrations.AlterField(
            model_name='atca',
            name='ra_path',
            field=tracet.models.fields.JXPathField(help_text='The (x|j)path to the Right Ascension. This value is set by the most recent matching notice.', max_length=500),
        ),
        migrations.AlterField(
            model_name='booleancondition',
            name='selector',
            field=tracet.models.fields.JXPathField(max_length=250),
        ),
        migrations.AlterField(
            model_name='equalitycondition',
            name='selector',
            field=tracet.models.fields.JXPathField(max_length=250),
        ),
        migrations.AlterField(
            model_name='mwacorrelator',
            name='dec_path',
            field=tracet.models.fields.JXPathField(help_text='The (x|j)path to the Declination. This value is set by the most recent matching notice.', max_length=500),
        ),
        migrations.AlterField(
            model_name='mwacorrelator',
            name='ra_path',
            field=tracet.models.fields.JXPathField(help_text='The (x|j)path to the Right Ascension. This value is set by the most recent matching notice.', max_length=500),
        ),
        migrations.AlterField(
            model_name='mwagw',
            name='skymap_path',
            field=tracet.models.fields.JXPathField(help_text='The (x|j)path to the embedded skymap. This value is set by the most recent matching notice.', max_length=500),
        ),
        migrations.AlterField(
            model_name='mwavcs',
            name='dec_path',
            field=tracet.models.fields.JXPathField(help_text='The (x|j)path to the Declination. This value is set by the most recent matching notice.', max_length=500),
        ),
        migrations.AlterField(
            model_name='mwavcs',
            name='ra_path',
            field=tracet.models.fields.JXPathField(help_text='The (x|j)path to the Right Ascension. This value is set by the most recent matching notice.', max_length=500),
        ),
        migrations.AlterField(
            model_name='numericrangecondition',
            name='selector',
            field=tracet.models.fields.JXPathField(max_length=250),
        ),
    ]
