# Generated by Django 6.0 on 2026-01-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracet', '0061_alter_atca_dec_path_alter_atca_ra_path_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='event',
            name='tracet_even_groupid_ebc7ca_idx',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='groupid',
            new_name='eventid',
        ),
        migrations.RenameField(
            model_name='trigger',
            old_name='groupby',
            new_name='eventid_path',
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['eventid'], name='tracet_even_eventid_359ee3_idx'),
        ),
    ]
