# Generated by Django 6.0 on 2026-01-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracet', '0062_remove_event_tracet_even_groupid_ebc7ca_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trigger',
            name='eventid_path',
            field=models.CharField(help_text='The (x|j)json path to event ID. This value is a unique classifier that groups one or more notices that are related to the same underlying event.', max_length=500, verbose_name='Event ID Path'),
        ),
    ]
