# Generated by Django 6.0 on 2026-01-23 08:16

import tracet.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracet', '0063_alter_trigger_eventid_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trigger',
            name='eventid_path',
            field=tracet.models.fields.JXPathField(help_text='The (x|j)json path to event ID. This value is a unique classifier that groups one or more notices that are related to the same underlying event.', max_length=500, verbose_name='Event ID Path'),
        ),
        migrations.AlterField(
            model_name='trigger',
            name='time_path',
            field=tracet.models.fields.JXPathField(help_text='The (x|j)json path to event time. This value is set by the first matching notice and is not overridden by subsequent notices.', max_length=500),
        ),
    ]
