# Generated by Django 6.0 on 2026-01-27 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracet', '0064_alter_trigger_eventid_path_alter_trigger_time_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mwagw',
            name='tileset',
        ),
    ]
