# Generated by Django 6.0 on 2026-01-29 08:02

import tracet.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracet', '0065_remove_mwagw_tileset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mwagw',
            name='skymap_path',
            field=tracet.models.fields.JXPathField(help_text='The (x|j)path to either: a URL to a FITS image; or a FITS image embedded directly in the notice using a Base64 encoding. This value is set by the most recent matching notice.', max_length=500),
        ),
    ]
