# Generated by Django 6.0 on 2026-02-04 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracet', '0066_alter_mwagw_skymap_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='decision',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='tracet.decision'),
        ),
    ]
