# Generated by Django 6.0 on 2026-02-04 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracet', '0067_alter_observation_decision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='istest',
        ),
    ]
