# Generated by Django 6.0 on 2026-02-06 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracet', '0068_remove_notice_istest'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='offset',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
