# Generated by Django 6.0 on 2026-02-06 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracet', '0069_notice_offset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='offset',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='notice',
            unique_together={('stream', 'offset')},
        ),
    ]
