# Generated by Django 6.0 on 2026-02-06 09:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracet', '0070_alter_notice_offset_alter_notice_unique_together'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notice',
            name='tracet_noti_created_533d2a_idx',
        ),
        migrations.AddField(
            model_name='notice',
            name='received',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='notice',
            name='created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='offset',
            field=models.IntegerField(),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['created', 'received'], name='tracet_noti_created_af8e27_idx'),
        ),
    ]
