# Generated by Django 6.0 on 2026-02-09 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracet', '0071_remove_notice_tracet_noti_created_533d2a_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gcnstream',
            old_name='name',
            new_name='topic',
        ),
    ]
