# Generated by Django 6.0 on 2026-02-09 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracet', '0072_rename_name_gcnstream_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='gcnstream',
            name='status',
            field=models.CharField(default='—', max_length=500),
        ),
    ]
