# Generated by Django 6.0 on 2026-02-10 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracet', '0073_gcnstream_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GCNStream',
            new_name='Topic',
        ),
        migrations.RenameField(
            model_name='notice',
            old_name='stream',
            new_name='topic',
        ),
        migrations.RenameField(
            model_name='trigger',
            old_name='streams',
            new_name='topics',
        ),
        migrations.AlterUniqueTogether(
            name='notice',
            unique_together={('topic', 'offset')},
        ),
    ]
