# Generated by Django 6.0 on 2026-02-10 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracet', '0074_rename_gcnstream_topic_rename_stream_notice_topic_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='topic',
            new_name='name',
        ),
    ]
