# Generated by Django 6.0 on 2026-02-10 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracet', '0075_rename_topic_topic_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='type',
            field=models.CharField(choices=[('xml', 'XML'), ('json', 'JSON')], default='xml', max_length=500, verbose_name='Format'),
        ),
    ]
