# Generated by Django 6.0 on 2026-02-10 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracet', '0076_alter_topic_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trigger',
            name='topics',
            field=models.ManyToManyField(to='tracet.topic'),
        ),
    ]
