# Generated by Django 6.0 on 2026-02-10 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracet', '0077_alter_trigger_topics'),
    ]

    operations = [
        migrations.RunSQL("ALTER TABLE tracet_trigger_streams RENAME TO tracet_trigger_topics;")
    ]
