# Generated by Django 6.0 on 2026-02-16 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracet', '0079_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
