# Generated by Django 5.2.7 on 2025-11-12 07:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GCNStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('type', models.CharField(choices=[('xml', 'XML'), ('json', 'JSON')], default='xml', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('payload', models.BinaryField()),
                ('istest', models.BooleanField(default=False)),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TraceT2App.gcnstream')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('active', models.BooleanField(default=False, help_text='Is this trigger active? Set to inactive during testing to avoid sending spurious triggers to observatories.')),
                ('groupby', models.CharField(max_length=500)),
                ('ra_path', models.CharField(max_length=500)),
                ('dec_path', models.CharField(max_length=500)),
                ('time_path', models.CharField(help_text='The (x|j)json path to event time. This value is set by the first matching event and is not overridden by subsequent events.', max_length=250)),
                ('streams', models.ManyToManyField(to='TraceT2App.gcnstream')),
            ],
        ),
        migrations.CreateModel(
            name='NumericRangeCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selector', models.CharField(max_length=250)),
                ('val1', models.FloatField(verbose_name='≥')),
                ('val2', models.FloatField(verbose_name='＜')),
                ('if_true', models.IntegerField(choices=[(1, 'Pass'), (0, 'Maybe'), (-1, 'Fail')])),
                ('if_false', models.IntegerField(choices=[(1, 'Pass'), (0, 'Maybe'), (-1, 'Fail')])),
                ('trigger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TraceT2App.trigger')),
            ],
        ),
        migrations.CreateModel(
            name='MWA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectid', models.CharField(max_length=500)),
                ('repointing_threshold', models.FloatField()),
                ('frequency', models.CharField(max_length=500)),
                ('frequency_resolution', models.FloatField()),
                ('time_resolution', models.FloatField()),
                ('minimum_altitude', models.FloatField()),
                ('maximum_window', models.IntegerField(help_text='The maximum window of time following an event in which observations maybe be scheduled. Observations will may be truncated to not exceed this window, and events occurring after this window will be ignored. [second]')),
                ('trigger', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='TraceT2App.trigger')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupid', models.CharField(max_length=500)),
                ('events', models.ManyToManyField(to='TraceT2App.event')),
                ('trigger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TraceT2App.trigger')),
            ],
        ),
        migrations.CreateModel(
            name='BooleanCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selector', models.CharField(max_length=250)),
                ('if_true', models.IntegerField(choices=[(1, 'Pass'), (0, 'Maybe'), (-1, 'Fail')])),
                ('if_false', models.IntegerField(choices=[(1, 'Pass'), (0, 'Maybe'), (-1, 'Fail')])),
                ('trigger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TraceT2App.trigger')),
            ],
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['-created'], name='TraceT2App__created_d518f6_idx'),
        ),
    ]
