# Generated by Django 5.2.7 on 2025-11-12 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TraceT2App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mwa',
            name='trigger',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='TraceT2App.trigger'),
        ),
    ]
