# Generated by Django 5.2.7 on 2025-11-12 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TraceT2App', '0002_alter_mwa_trigger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gcnstream',
            name='name',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
