# Generated by Django 5.2.7 on 2025-11-13 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TraceT2App', '0003_alter_gcnstream_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventgroup',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
