# Generated by Django 5.2.7 on 2025-11-21 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TraceT2App', '0004_eventgroup_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainsCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selector', models.CharField(max_length=250)),
                ('vals', models.TextField()),
                ('if_true', models.IntegerField(choices=[(1, 'Pass'), (0, 'Maybe'), (-1, 'Fail')])),
                ('if_false', models.IntegerField(choices=[(1, 'Pass'), (0, 'Maybe'), (-1, 'Fail')])),
                ('trigger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TraceT2App.trigger')),
            ],
        ),
    ]
