# Generated by Django 5.2.7 on 2025-11-21 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TraceT2App', '0005_containscondition'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='Notice',
        ),
        migrations.RenameIndex(
            model_name='notice',
            new_name='TraceT2App__created_d60b86_idx',
            old_name='TraceT2App__created_d518f6_idx',
        ),
        migrations.AlterField(
            model_name='trigger',
            name='time_path',
            field=models.CharField(help_text='The (x|j)json path to event time. This value is set by the first matching notice and is not overridden by subsequent notices.', max_length=250),
        ),
    ]
