# Generated by Django 5.2.7 on 2025-11-21 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TraceT2App', '0006_rename_event_notice_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventgroup',
            old_name='events',
            new_name='notices',
        ),
    ]
