# Generated by Django 5.2.7 on 2025-11-21 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TraceT2App', '0007_rename_events_eventgroup_notices'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventGroup',
            new_name='Event',
        ),
    ]
