# Generated by Django 5.2.7 on 2025-11-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TraceT2App', '0008_rename_eventgroup_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mwa',
            name='minimum_altitude',
        ),
        migrations.AddField(
            model_name='mwa',
            name='exposure',
            field=models.FloatField(default=120, help_text='The duration of each observation (for each frequency range). [second]'),
        ),
        migrations.AddField(
            model_name='mwa',
            name='nobs',
            field=models.IntegerField(default=15, help_text='The total number of observations. The total time will equal: (nobs) * (number of frequency ranges) * (exposure time)'),
        ),
        migrations.AlterField(
            model_name='mwa',
            name='frequency',
            field=models.CharField(help_text='A space separated list of MWA coarse channel specifications. A coarse channel is specified as a ', max_length=500),
        ),
        migrations.AlterField(
            model_name='mwa',
            name='frequency_resolution',
            field=models.FloatField(default=10, help_text='Correlator frequency resolution. [kHz]'),
        ),
        migrations.AlterField(
            model_name='mwa',
            name='time_resolution',
            field=models.FloatField(default=0.5, help_text='Correlator integration time. [second]'),
        ),
    ]
