# Generated by Django 5.2.7 on 2025-11-25 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TraceT2App', '0009_remove_mwa_minimum_altitude_mwa_exposure_mwa_nobs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mwa',
            name='password',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
