# Generated by Django 5.2.7 on 2025-11-25 06:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TraceT2App', '0010_mwa_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('observatory', models.CharField(max_length=500)),
                ('priority', models.IntegerField()),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('success', models.BooleanField()),
                ('log', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='mwa',
            name='frequency',
            field=models.CharField(help_text="A space separated list of MWA coarse channel specifications. The specification format is documented <a href='https://mwatelescope.atlassian.net/wiki/spaces/MP/pages/24972656/Triggering+web+services#Channel-selection-specifier-strings'>here.</a> For example: '145,24' will observe with 24 channels centered at channel 145; a space separated list like '121:24 145:160;165:170' will schedule two separate observations.", max_length=500),
        ),
    ]
