# Generated by Django 5.2.7 on 2025-11-25 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TraceT2App', '0011_observation_alter_mwa_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='trigger',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
