# Generated by Django 5.2.7 on 2025-11-26 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TraceT2App', '0012_trigger_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trigger',
            name='active',
        ),
        migrations.AddField(
            model_name='trigger',
            name='testing',
            field=models.BooleanField(default=True, help_text='When testing, observation requests sent to observatories will be marked as testing only.'),
        ),
    ]
