# Generated by Django 5.2.7 on 2025-11-26 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TraceT2App', '0013_remove_trigger_active_trigger_testing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trigger',
            name='testing',
        ),
        migrations.AddField(
            model_name='trigger',
            name='active',
            field=models.BooleanField(default=False, help_text='Inactive triggers will send observation requests to observatories marked as testing only.'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='success',
            field=models.CharField(choices=[('FAILED', 'Failed'), ('OK', 'OK'), ('TESTINGOK', 'OK (Testing)'), ('TESTINGFAILED', 'Failed (Testing)')]),
        ),
    ]
