# Generated by Django 5.2.7 on 2025-11-26 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TraceT2App', '0014_remove_trigger_testing_trigger_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observation',
            old_name='success',
            new_name='status',
        ),
    ]
