# Generated by Django 5.2.7 on 2025-11-26 03:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TraceT2App', '0015_rename_success_observation_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observation',
            old_name='end',
            new_name='finish',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='created',
        ),
        migrations.AlterField(
            model_name='observation',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
