# Generated by Django 5.2.7 on 2025-11-26 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TraceT2App', '0016_rename_end_observation_finish_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='status',
            field=models.CharField(choices=[('FAILED', 'Failed'), ('OK', 'OK'), ('TESTING_OK', 'OK (Testing)'), ('TESTING_FAILED', 'Failed (Testing)')]),
        ),
    ]
