# Generated by Django 5.2.7 on 2025-11-26 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TraceT2App', '0017_alter_observation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observation',
            name='status',
        ),
        migrations.AddField(
            model_name='observation',
            name='istest',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='observation',
            name='success',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
