# Generated by Django 5.2.7 on 2025-11-26 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TraceT2App', '0018_remove_observation_status_observation_istest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TraceT2App.event'),
        ),
        migrations.AddField(
            model_name='observation',
            name='trigger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TraceT2App.trigger'),
        ),
    ]
