# Generated by Django 5.2.7 on 2025-11-26 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TraceT2App', '0019_observation_event_observation_trigger'),
    ]

    operations = [
        migrations.CreateModel(
            name='ATCA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectid', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='BandConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band', models.IntegerField(choices=[(3, '3 mm'), (7, '6 mm'), (15, '15 mm'), (40, '4 cm'), (160, '16 cm')])),
                ('freq1', models.IntegerField()),
                ('freq2', models.IntegerField()),
                ('atca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TraceT2App.atca')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('atca', 'band'), name='unique wavelength configuration')],
            },
        ),
    ]
