# Generated by Django 5.2.7 on 2025-11-26 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TraceT2App', '0020_atca_bandconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='atca',
            name='trigger',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='TraceT2App.trigger'),
            preserve_default=False,
        ),
    ]
