# Generated by Django 5.2.7 on 2025-11-26 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TraceT2App', '0021_atca_trigger'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BandConfig',
            new_name='ATCABand',
        ),
    ]
