# Generated by Django 5.2.7 on 2025-11-26 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TraceT2App', '0022_rename_bandconfig_atcaband'),
    ]

    operations = [
        migrations.AddField(
            model_name='atca',
            name='authentication_token',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atca',
            name='email',
            field=models.EmailField(default='', help_text='The email address that was supplied in the NAPA proposal.', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atca',
            name='http_password',
            field=models.CharField(default='', max_length=500, verbose_name='HTTP Password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atca',
            name='http_username',
            field=models.CharField(default='', max_length=500, verbose_name='HTTP Username'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atca',
            name='maximum_exposure',
            field=models.IntegerField(default=120, help_text='The maximum exposure time required for this trigger. [minute]'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atca',
            name='maximum_lag',
            field=models.FloatField(default=600, help_text='The maximum amount of time in the future we will allow the start time to be. [minute]'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atca',
            name='minimum_exposure',
            field=models.IntegerField(default=30, help_text='The minimum exposure time required for this trigger. The trigger will be rejected if ATCA cannot schedule a total exposure of at least this time. [minute]'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atcaband',
            name='exposure',
            field=models.IntegerField(default=1, help_text='The exposure time of this reciever. Receivers will be continuously cycled up until the full scheduled slot is exhausted. [minute]'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='atcaband',
            name='freq1',
            field=models.IntegerField(help_text='Specify the central frequency for the first of the 2 GHz bands at which this receiver will observe. Note: the 16 cm reciever can only observe at 2100 MHz. [MHz]'),
        ),
        migrations.AlterField(
            model_name='atcaband',
            name='freq2',
            field=models.IntegerField(help_text='Specify the central frequency for the second of the 2 GHz bands at which this receiver will observe. Note: the 16 cm reciever can only observe at 2100 MHz. [MHz]'),
        ),
    ]
