# Generated by Django 5.2.7 on 2025-11-27 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TraceT2App', '0023_atca_authentication_token_atca_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mwa',
            name='tileset',
            field=models.CharField(choices=[('all_on', 'All'), ('phase_one', 'Phase 1'), ('p1+hexes', 'Phase 1 + Hexes'), ('p1+solar', 'Phase 1 + Solar'), ('p2_compact', 'Phase 2 Compact'), ('p2_extended', 'Phase 2 Extended'), ('256T', '256 tiles')], default='256T', help_text='Select the set of tiles to use for this observation. More tiles gives better sensitivity but at the expense large data requirements.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='atca',
            name='maximum_lag',
            field=models.FloatField(help_text='The maximum delay allowed for scheduling this observation. If the observation cannot be scheduled to start within this time, it will not be scheduled at all. [minute]'),
        ),
        migrations.AlterField(
            model_name='atcaband',
            name='band',
            field=models.IntegerField(choices=[(3, '3mm'), (7, '6mm'), (15, '15mm'), (40, '4cm'), (160, '16cm')]),
        ),
    ]
