# Generated by Django 5.2.7 on 2025-11-27 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TraceT2App', '0024_mwa_tileset_alter_atca_maximum_lag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mwa',
            name='tileset',
            field=models.CharField(choices=[('phase_one', 'Phase 1'), ('p1+hexes', 'Phase 1 + Hexes'), ('p1+solar', 'Phase 1 + Solar'), ('p2_compact', 'Phase 2 Compact'), ('p2_extended', 'Phase 2 Extended'), ('256T', '256 tiles')], help_text='Select the set of tiles to use for this observation. More tiles gives better sensitivity but at the expense larger data requirements.'),
        ),
    ]
