# Generated by Django 6.0 on 2025-12-15 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TraceT2App', '0035_alter_observation_decision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='decision',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observations', to='TraceT2App.decision'),
        ),
    ]
