# Generated by Django 6.0 on 2025-12-16 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TraceT2App', '0037_alter_observation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='observatory',
            field=models.CharField(choices=[('atca', 'ATCA'), ('mwa', 'MWA')], max_length=500),
        ),
        migrations.AlterField(
            model_name='observation',
            name='status',
            field=models.CharField(choices=[('api_ok', 'OK'), ('api_failure', 'Failure'), ('clash', 'Clashing observation'), ('request_failure', 'Could not make API request'), ('data_failure', 'Unable to prepare request')]),
        ),
    ]
