# Generated by Django 6.0 on 2025-12-17 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TraceT2App', '0044_auto_20251217_0159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trigger',
            name='dec_path',
        ),
        migrations.RemoveField(
            model_name='trigger',
            name='ra_path',
        ),
    ]
