# Generated by Django 6.0 on 2025-12-17 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TraceT2App', '0045_remove_trigger_dec_path_remove_trigger_ra_path'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MWA',
            new_name='MWACorrelator',
        ),
    ]
